package com.example.roamify.tourbooking.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a single row in the 'users' table in the database.
 * Each instance of this class is a user account.
 *
 * @param userId The unique ID for the user, auto-generated by Room.
 * @param name The user's full name, which will be used for logging in.
 * @param phoneNumber The user's phone number.
 * @param password The user's password. In a real app, this should be hashed.
 */
@Entity(tableName = "users")
data class User(
    @PrimaryKey(autoGenerate = true)
    val userId: Int = 0,
    val name: String,
    val phoneNumber: String,
    val password: String
)
